language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
  - openjdk8

branches:
  only:
  - master

before_install:
  - cd owlsim-core; make; ulimit -u 514029

after_success:
  - mvn clean cobertura:cobertura coveralls:report
